on: 
  workflow_dispatch: 
    inputs: 
      enviroment:
        description: "choose enviroment"
        required: true
        default: "stagin"
        type: choice
        options: 
          - stagin
          - production


jobs:
    deploy:
      runs-on: ubuntu-latest
      steps:
        - name: Deploy applications 
          run: echo "Deploying the applications...."
