on: 
  repository_dispatch:
    types: [incident_report]

jobs:
  handel-incident:
    runs-on: ubuntu-latest
    steps: 
      - name: print incident details
        run: echo "Incident reported"
  
